### ISSUE TITLE
Suggestions on the project with Chrome 44 :)

### ISSUE THREAD

**Issue by derkmdt** [blittle/chrome-dev-tools#8]
Hi Bret,

Love your "Down and Dirty with Chrome Dev Tools", really learned from it!

I see you already made a issue where you say you should update this on newer versions. But still I would like to give my 2 cents.

Ik have the following setting:
- UserAgent:
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36

When walking though the topics I had the below comments/suggestions/experience:
- http://blittle.github.io/chrome-dev-tools/sources/skip-frameworks.html 
  - option not available any more in "experiments"
- http://blittle.github.io/chrome-dev-tools/sources/web-workers.html 
  - don't see the workers option in my Chrome web-inspector/sources. Where can I find them/enable them.
- http://blittle.github.io/chrome-dev-tools/sources/maps.html 
  - this option seems to be not available any more. Think it's default now, it works as you say it does.
- http://blittle.github.io/chrome-dev-tools/timeline/README.html 
  - example explanation, didn't know what todo on this question + answer
- http://blittle.github.io/chrome-dev-tools/profiles/README.html 
  -example explanation, didn't know what todo on this question + answer
- http://blittle.github.io/chrome-dev-tools/console/README.html 
  - example explanation, didn't know what todo on this question + answer
- http://blittle.github.io/chrome-dev-tools/console/monitor-events.html 
  - doesn't work out of the box when doing "monitorEvents($x('//*[@id="section-gitbook_10"]/textarea'), ["scroll"]);" for example. Also the "monitorEvents(window, ["scroll"]);" doesn't work on this page. Other pages it does, so probably the setting on this project doesn't work (css with divs or something?).

Regards,
Derk

**Comment by blittle** [comment]
Derk, part of the reason I need to redo the project on the latest version of gitbook is because gitbook currently behaves differently when you hard refresh load a page versus navigating to a page when the book is already loaded. For the examples, until I get things ported over, I'd recommend doing a hard refresh on each page when you are trying to look at the examples.

That said, chrome has changed and along with my port I need to update the content to reflect the latest version of Chrome. Thank you for gathering specifics that need to be upgraded.

**Comment by derkmdt** [comment]
Thx for the quick rersponse. I'll try your suggestion!
